### PR TITLE
initial README commit with forest logo

### LINKED ISSUE #18: Flesh out README.md
We need to set up the README with some information.

### PR DESCRIPTION
**Pull request by nicklafarge**
A basic readme in place with links to the the most useful existing pages

### CODE REVIEW

**Comment by nicklafarge** [comment]
I'm sure we will want to add more to this as we go, but I figured it would be good to get something in place so that when I email the group instructions to create GitHub accounts / join the project, they at least have some basic information/links on the main page.

**Comment by rjpower4** [comment]
What is the purpose of the "dev" image. Also, I assume the main logo was obtained via some sort of stable diffusion thing? Are we totally sure we have distribution rights?

**Comment by nicklafarge** [comment]
Correct it's stable diffusion. i looked into it and my understanding is that we can use it with to restrictions. I thought the dev one would be fun for the wiki, buts it's not very important and we can always change it later

**Review by rjpower4 — APPROVED** [review]
LGTM

**Pull request merged**
